services:
  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - PORT=3006
    depends_on:
      - db
    networks:
      - web

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web

volumes:
  pgdata:

networks:
  web:
    external: true
